on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/30 * * * *'      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub - Activity - Readme
      uses: jamesgeorge007/github-activity-readme@v0.1.7
      with:
        USERNAME: Novvan
